   export const ARTISTS = [
        "Taylor Swift",
        "Drake",
        "The Weeknd",
        "Ariana Grande",
        "Ed Sheeran",
        "Olivia Rodrigo",
        "Dua Lipa",
        "Justin Bieber",
        "Harry Styles",
        "Billie Eilish",
        "Post Malone",
        "Doja Cat",
        "SZA",
        "Khalid",
        "Shawn Mendes",
        "Maroon 5",
        "Bruno Mars",
        "Rihanna",
        "Katy Perry",
        "Imagine Dragons",
        "twenty one pilots",
        "Arctic Monkeys",
        "Charlie Puth",
        "David Guetta",
        "OneRepublic",
        "Marshmello",
        "Juice WRLD",
        "Coldplay",
        "Benson Boone",
        "HUNTR/X",
        "Avicii",
        "Weezer",
        "Bastille",
        "Michael Jackson",
        "Myles Smith",
        "Panic! At The Disco",
        "U2",
        "Usher",
        "Ava Max",
        "Daft Punk",
        "Snoop Dogg",
    ];